# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-18 12:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190618_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 18, 12, 28, 12, 683339, tzinfo=utc)),
        ),
    ]
