# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-19 03:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190618_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='create_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2019, 6, 19, 3, 47, 15, 387531, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
