# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-19 03:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190619_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 19, 3, 48, 14, 576534, tzinfo=utc)),
        ),
    ]
