# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-19 03:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190619_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 19, 3, 50, 17, 774536, tzinfo=utc)),
        ),
    ]
